name: jjgsr
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  provider: ^6.1.2
  firebase_core: ^3.1.0
  cloud_firestore: ^5.0.1
  firebase_analytics: ^11.0.1
  firebase_crashlytics: ^4.0.1
  firebase_remote_config: ^5.0.1
  custom_refresh_indicator: ^3.1.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  build_runner: ^2.4.7
  hive_generator: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  flutter_oss_licenses: ^3.0.2

flutter:

  uses-material-design: true
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Black.ttf
        - asset: assets/fonts/Inter-Bold.ttf
        - asset: assets/fonts/Inter-ExtraBold.ttf
        - asset: assets/fonts/Inter-ExtraLight.ttf
        - asset: assets/fonts/Inter-Light.ttf
        - asset: assets/fonts/Inter-Medium.ttf
        - asset: assets/fonts/Inter-Regular.ttf
        - asset: assets/fonts/Inter-SemiBold.ttf
        - asset: assets/fonts/Inter-Thin.ttf
    - family: Jua
      fonts:
        - asset: assets/fonts/Jua-Regular.ttf